version: "3"
services:
  db:
    build:
      context: .
      dockerfile: Dockerfile-DB
    env_file:
      - .env
    volumes:
      - ./db/data/postgres:/var/lib/postgresql/data  
    ports:
      - "5432:5432"
  backend:
    build: .
    working_dir: /home/app/backend
    environment:
      - PORT_POSTGRES=5432
      - HOST_POSTGRES=db
    volumes:
      - .:/home/app/backend
    command: ["./wait-for-db.sh", "node",  "index.js"]
    ports:
      - "3000:3000"
    depends_on:
      - db
  